# Generated by Django 4.2.1 on 2023-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (None, "(Unknown)"),
                    (1, "Admin"),
                    (2, "Manager"),
                    (3, "Client"),
                ],
                default=3,
            ),
        ),
    ]
